server:
  port: 8080
spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/new_scuola
    username: postgres
    password: 1234567890
    driver-class-name: org.postgresql.Driver
jpa:
  hibernate:
    ddl-auto: validate
  show-sql: true
  database-platform: org.hibernate.dialect.PostgreSQLDialect

